### ISSUE TITLE
[Feature Request] add parameter to disable clear screen

### ISSUE THREAD

**Issue by Nymphxyz** [mjishnu/pypdl#27]
Hi, I notice in the new version the progress bar will clear the whole screen.

It will be better to add a new parameter in the `start` function to let user to control whether to clear the screen.

Thank you!

**Comment by mjishnu** [comment]
i get what you mean in ideal cases there is no need to clear the screen but its needed when we want to remove broken elements in the console caused by mishaps like adjusting the width of the terminal while the progess bar is shown in it. this causes weird artifacts to form and the clearing just makes the screen neat during these edge cases. its true that it wont stop them but it prevents the console from looking too ugly.
![Screenshot 2024-11-10 003150](https://github.com/user-attachments/assets/932cb0d6-4d4f-401b-a86a-5a505b4a7c87)

in the above screenshot i adjusted the terminal width while progress bar was still shown this made it to display these misaligned artifacts.

If you want to disable the screen clearing just go to utils in your local machine and comment/remove the line which has the comment saying clear screen

![Screenshot 2024-11-10 003013](https://github.com/user-attachments/assets/1e09c589-f603-4341-8fc6-6b86eb80aebf)

if you are running in ideal condition, it shouldn't give you any issue, also be sure to add the `sys.stdout.write("\n") ` since without it the cursor starts writing from the previous line making you lose a line of previous data.
```py

class ScreenCleaner:
    """A context manager to clear the screen and hide cursor."""

    def __init__(self, display: bool):
        self.display = display

    def clear(self) -> None:
        sys.stdout.write("\n")  # Insert newlines
        # sys.stdout.write("\033c")  # Clear screen
        sys.stdout.write("\x1b[?25l")  # Hide cursor

    def __enter__(self):
        if self.display:
            self.clear()
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        if self.display:
            sys.stdout.write("\x1b[?25h")  # Show cursor

```
here is the full code in case you need it

the reason why i am not implementing this as a parameter in start method is since its already complex and I don't want to increase the complexity anymore unless it's needed by a lot. if i get more request for this i will implement it currently since i don't think it is needed for most i will keep this as such.

**Comment by syntaxsurge** [comment]
> condition, it shouldn't give you any issue, also be sure to add the `sys.stdout.write("\n") ` since without it the cursor starts writing from the previous line making you lose a line of previous

I suggest adding it as a parameter, because I am running it in a docker container, when I do something like this:
`docker logs -f my_container`

That don't retain the previous logs after clearing the screen. I have important logs that I want to see and I don't want to clear the screen.
It's time-consuming to fork your repo just to implement that feature.
It's just my suggestion, thank you!

**Comment by mjishnu** [comment]
> > condition, it shouldn't give you any issue, also be sure to add the `sys.stdout.write("\n") ` since without it the cursor starts writing from the previous line making you lose a line of previous
> 
> 
> 
> I suggest adding it as a parameter, because I am running it in a docker container, when I do something like this:
> 
> `docker logs -f my_container`
> 
> 
> 
> That don't retain the previous logs after clearing the screen. I have important logs that I want to see and I don't want to clear the screen.
> 
> It's time-consuming to fork your repo just to implement that feature.
> 
> It's just my suggestion, thank you!

i never tested in docker, i see that seem to be a valid reason i will implement it then.

**Comment by mjishnu** [comment]
hello, i have added this to [v1.4.5](https://test.pypi.org/project/pypdl/1.4.5/) can you guys test it out and see if its fixing the issue for you @syntaxsurge @Nymphxyz. you can set it by using `clear_terminal `argument in `start `method also note some of the positions of arguments have changed so check docs if you are getting errors

you can test this version from here: [https://test.pypi.org/project/pypdl/1.4.5/](https://test.pypi.org/project/pypdl/1.4.5/)

**Comment by Nymphxyz** [comment]
LGTM.
